### ISSUE TITLE
教程里的配置出现笔误，配置无法更改 xml 文件

### ISSUE THREAD

**Issue by hayschan** [bestony/hexo-generator-podcasts#14]
关于设置播客 `config.xml` 里的[示例 1 ](https://github.com/bestony/hexo-generator-podcasts#for-single-podcast) 和 [示例 2](https://github.com/bestony/hexo-generator-podcasts/#for-multiple-podcast) 都出现了笔误，podcast 后面多了一个 s。
示例里是这样：
```yaml
podcasts:
  - name: "podcast"
    path: "feed/podcast"
```
把 s 删掉，`podcasts` 改成 `podcast`，才能用：
```yaml
podcast:
  - name: "podcast"
    path: "feed/podcast"
```
